apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctalk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: gcr.io/semiotic-sylph-450506-u5/web-app:latest
          ports:
            - containerPort: 80
