apiVersion: v1
kind: Service
metadata:
  name: kafka-external
spec:
  type: LoadBalancer
  ports:
    - name: kafka
      port: 9094
      targetPort: 9092
  selector:
    app.kubernetes.io/name: kafka