apiVersion: v1
kind: Service
metadata:
  name: doctalk
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  selector:
    app: doctalk
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080