spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


server:
  address: 0.0.0.0
  port: 8443
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/blaybus-glowup.com/keystore.p12
    key-store-password: blaybus
    key-store-type: PKCS12
    key-alias: blaybus
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024 # 1KB ??? ??? ?? ??