spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


server:
  address: 0.0.0.0
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024 # 1KB ??? ??? ?? ??